### PR TITLE
Add build-depend on pkg-config to find urdfdom

### PR DESCRIPTION
**Pull request by scpeters**
I noticed that the 10.7.0~pre1 debbuilds failed to compile some tests with complaints about finding urdf headers:

* [Build Status](https://build.osrfoundation.org/job/sdformat10-debbuilder/242/) https://build.osrfoundation.org/job/sdformat10-debbuilder/242

~~~
src/parser_urdf.cc:30:10: fatal error: urdf_model/model.h: No such file or directory
 #include <urdf_model/model.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/UNIT_ParamPassing_TEST.dir/build.make:257: recipe for target
 'src/CMakeFiles/UNIT_ParamPassing_TEST.dir/parser_urdf.cc.o' failed
~~~

It turns out there was a bug in 10.7.0~pre1 when `USE_INTERNAL_URDF == TRUE`, and the debbuilds were unintentionally failing to find the external urdfdom since `pkg-config` was not found. I've added `pkg-config` as a `build-depend` in the control file here, which should fix the 10.7.0~pre1 builds.

Separately, I've submitted a fix for the compilation error when `USE_INTERNAL_URDF == TRUE` in https://github.com/ignitionrobotics/sdformat/pull/800

### CODE REVIEW

**Comment by scpeters** [comment]
testing

* [Build Status](https://build.osrfoundation.org/job/sdformat10-debbuilder/245/) https://build.osrfoundation.org/job/sdformat10-debbuilder/245/

**Comment by scpeters** [comment]
> testing
> 
> * [Build Status](https://build.osrfoundation.org/job/sdformat10-debbuilder/245/) https://build.osrfoundation.org/job/sdformat10-debbuilder/245/

it's unstable because the `sdformat10-all` cmake files are not installed. that should be fixed by https://github.com/ignition-release/sdformat10-release/pull/7/commits/910cfcc112bcef4ce40b85f14b78a7de7d283431

testing again:

* [Build Status](https://build.osrfoundation.org/job/sdformat10-debbuilder/246/) https://build.osrfoundation.org/job/sdformat10-debbuilder/246/

**Comment by scpeters** [comment]
> > testing
> > 
> > * [Build Status](https://build.osrfoundation.org/job/sdformat10-debbuilder/245/) https://build.osrfoundation.org/job/sdformat10-debbuilder/245/
> 
> it's unstable because the `sdformat10-all` cmake files are not installed. that should be fixed by [910cfcc](https://github.com/ignition-release/sdformat10-release/commit/910cfcc112bcef4ce40b85f14b78a7de7d283431)
> 
> testing again:
> 
> * [Build Status](https://build.osrfoundation.org/job/sdformat10-debbuilder/246/) https://build.osrfoundation.org/job/sdformat10-debbuilder/246/

~~oddly, the FindIgnURDFDOM module seems to work on 20.04 but not 18.04~~ I think it's not the find module, but the logic for which packages are installed as dependencies on the system seems to differ by platform, and I don't know why

**Comment by scpeters** [comment]
I've filed https://github.com/ignition-tooling/release-tools/issues/606 to track the issue of using the system `liburdfdom` in our debian binary packages in case we don't have time to resolve this for the final libsdformat10 release.

**Comment by scpeters** [comment]
we'll address this for other versions
